# Default values for me-map-service
# Declare variables to be passed into your templates.
global:
  environment: "ci"
  aws_default_region: "eu-west-1"

## image configuration
image:
  repository: 747203990113.dkr.ecr.eu-west-1.amazonaws.com
  name: me-esri-webmaps
  tag: TBD
  pullPolicy: Always

## checking pods status
ports:
  targetPort: 3000
checkReady: true
readyPath: "/"
healthzPath: "/"
initialDelaySeconds: 90
periodSeconds: 3
failureThreshold: 30

safety:
  webmapId: "906b58f399944774a29e05d3d24a939b"

mobility:
  webmapId: "0b800d1e71d94002b8d2451dcd08155d"

events:
  webmapId: "37f6876be7dc4d7e8166c3ef0df0c3aa"

survey:
  webmapId: "3a979480c3644b2d91cf4053af9568b9"

### how many replica for application
replicas: 3

## exposing service out-side
expose: true
nodePorts:
  useFixed: true
  product:
   http: 31925

## resources allocation
#resources:
#  limits:
#    memory: 900Mi
#    cpu: 1030m
#  requests:
#    memory: 50Mi
#    cpu: 150m


