apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  environment: {{ .Values.global.environment }}
  aws_default_region: {{ .Values.global.aws_default_region }}
  safety_webmap_id: {{ .Values.webmapId }}
  mobility_webmap_id: {{ .Values.webmapId }}
  events_webmap_id: {{ .Values.webmapId }}
  survey_webmap_id: {{ .Values.webmapId }}