apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  environment: {{ .Values.global.environment }}
  aws_default_region: {{ .Values.global.aws_default_region }}
  webmap_id: {{ .Values.webmapId }}